# Generated by Django 5.0.2 on 2025-08-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_default_tax_rate'),
        ('users', '0004_user_username_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_level',
            field=models.PositiveIntegerField(default=1, help_text="Niveau d'approbation pour les workflows (1 = basique, 5 = directeur)", verbose_name="Niveau d'approbation"),
        ),
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text="Entreprises auxquelles l'utilisateur a accès", related_name='users_many', to='companies.company', verbose_name='Sociétés membres'),
        ),
    ]
