# Generated by Django 5.0.2 on 2025-08-22 19:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "unit_price_ht",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Prix unitaire HT",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Remise (%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Remise (montant)",
                    ),
                ),
                (
                    "total_line_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total ligne HT",
                    ),
                ),
                (
                    "total_line_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total ligne TVA",
                    ),
                ),
                (
                    "total_line_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total ligne TTC",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Ligne de document",
                "verbose_name_plural": "Lignes de document",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code séquence"
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=50, unique=True, verbose_name="Numéro"),
                ),
                (
                    "issue_date",
                    models.DateField(auto_now_add=True, verbose_name="Date d'émission"),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyé"),
                            ("approved", "Approuvé"),
                            ("validated", "Validé"),
                            ("paid", "Payé"),
                            ("partial", "Partiellement payé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MAD", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=10,
                        verbose_name="Taux de change",
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total HT",
                    ),
                ),
                (
                    "total_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total TVA",
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Remise (%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Remise (montant)",
                    ),
                ),
                (
                    "withholding_tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Retenue à la source (%)",
                    ),
                ),
                (
                    "withholding_tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Retenue à la source (montant)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("terms", models.TextField(blank=True, verbose_name="Conditions")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[("sale", "Vente"), ("purchase", "Achat")],
                        default="sale",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "payment_terms",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Conditions de paiement (jours)"
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(default=False, verbose_name="Comptabilisé"),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Comptabilisé le"
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Encaissement"),
                            ("disbursement", "Décaissement"),
                        ],
                        default="receipt",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Espèces"),
                            ("transfer", "Virement"),
                            ("check", "Chèque"),
                            ("card", "Carte bancaire"),
                            ("other", "Autre"),
                        ],
                        default="transfer",
                        max_length=20,
                        verbose_name="Moyen de paiement",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MAD", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=10,
                        verbose_name="Taux de change",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                (
                    "check_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Numéro de chèque"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom de la banque"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "value_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de valeur"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "is_reconciled",
                    models.BooleanField(default=False, verbose_name="Rapproché"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_id", models.PositiveIntegerField()),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant alloué",
                    ),
                ),
                (
                    "reconciliation_group",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="Groupe de lettrage",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Allocation de paiement",
                "verbose_name_plural": "Allocations de paiement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code séquence"
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=50, unique=True, verbose_name="Numéro"),
                ),
                (
                    "issue_date",
                    models.DateField(auto_now_add=True, verbose_name="Date d'émission"),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyé"),
                            ("approved", "Approuvé"),
                            ("validated", "Validé"),
                            ("paid", "Payé"),
                            ("partial", "Partiellement payé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MAD", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=10,
                        verbose_name="Taux de change",
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total HT",
                    ),
                ),
                (
                    "total_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total TVA",
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Remise (%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Remise (montant)",
                    ),
                ),
                (
                    "withholding_tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Retenue à la source (%)",
                    ),
                ),
                (
                    "withholding_tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Retenue à la source (montant)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("terms", models.TextField(blank=True, verbose_name="Conditions")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("purchase", "Achat"), ("sale", "Vente")],
                        default="purchase",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(blank=True, verbose_name="Adresse de livraison"),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de livraison souhaitée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de commande",
                "verbose_name_plural": "Bons de commande",
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code séquence"
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=50, unique=True, verbose_name="Numéro"),
                ),
                (
                    "issue_date",
                    models.DateField(auto_now_add=True, verbose_name="Date d'émission"),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyé"),
                            ("approved", "Approuvé"),
                            ("validated", "Validé"),
                            ("paid", "Payé"),
                            ("partial", "Partiellement payé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MAD", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=10,
                        verbose_name="Taux de change",
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total HT",
                    ),
                ),
                (
                    "total_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total TVA",
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Remise (%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Remise (montant)",
                    ),
                ),
                (
                    "withholding_tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Retenue à la source (%)",
                    ),
                ),
                (
                    "withholding_tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Retenue à la source (montant)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("terms", models.TextField(blank=True, verbose_name="Conditions")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "validity_days",
                    models.PositiveIntegerField(
                        choices=[
                            (15, "15 jours"),
                            (30, "30 jours"),
                            (60, "60 jours"),
                            (90, "90 jours"),
                        ],
                        default=30,
                        verbose_name="Validité (jours)",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Valide jusqu'au"
                    ),
                ),
                (
                    "is_converted",
                    models.BooleanField(default=False, verbose_name="Converti"),
                ),
            ],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
            },
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code séquence"
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=50, unique=True, verbose_name="Numéro"),
                ),
                (
                    "issue_date",
                    models.DateField(auto_now_add=True, verbose_name="Date d'émission"),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyé"),
                            ("approved", "Approuvé"),
                            ("validated", "Validé"),
                            ("paid", "Payé"),
                            ("partial", "Partiellement payé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MAD", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=10,
                        verbose_name="Taux de change",
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total HT",
                    ),
                ),
                (
                    "total_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total TVA",
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Remise (%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Remise (montant)",
                    ),
                ),
                (
                    "withholding_tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Retenue à la source (%)",
                    ),
                ),
                (
                    "withholding_tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Retenue à la source (montant)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("terms", models.TextField(blank=True, verbose_name="Conditions")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "credit_type",
                    models.CharField(
                        choices=[
                            ("full", "Annulation totale"),
                            ("partial", "Annulation partielle"),
                            ("discount", "Remise/Escompte"),
                        ],
                        default="partial",
                        max_length=20,
                        verbose_name="Type d'avoir",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Motif")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_documents",
                        to="companies.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avoir",
                "verbose_name_plural": "Avoirs",
            },
        ),
    ]
