# Generated by Django 5.0.2 on 2025-08-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("catalog", "0001_initial"),
        ("companies", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_documents",
                to="crm.party",
                verbose_name="Partie",
            ),
        ),
        migrations.AddField(
            model_name="documentline",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="documentline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_lines",
                to="catalog.product",
                verbose_name="Produit/Service",
            ),
        ),
        migrations.AddField(
            model_name="documentline",
            name="tax_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_lines",
                to="catalog.taxrate",
                verbose_name="Taux de TVA",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_documents",
                to="companies.company",
                verbose_name="Société",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_documents",
                to="crm.party",
                verbose_name="Partie",
            ),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="original_invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_notes",
                to="billing.invoice",
                verbose_name="Facture d'origine",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="companies.company",
                verbose_name="Société",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="crm.party",
                verbose_name="Partie",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="billing.payment",
                verbose_name="Paiement",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_documents",
                to="companies.company",
                verbose_name="Société",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_documents",
                to="crm.party",
                verbose_name="Partie",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="billing.purchaseorder",
                verbose_name="Bon de commande",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_documents",
                to="companies.company",
                verbose_name="Société",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="converted_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_from",
                to="billing.quote",
                verbose_name="Converti en",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_documents",
                to="crm.party",
                verbose_name="Partie",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="billing.quote",
                verbose_name="Devis d'origine",
            ),
        ),
    ]
