# Generated by Django 5.0.2 on 2025-08-22 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="converted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Converti le"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="converted_po",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="origin_quotes",
                to="billing.purchaseorder",
                verbose_name="Bon de commande généré",
            ),
        ),
    ]
