# Generated by Django 5.0.2 on 2025-08-22 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_quote_converted_at_quote_converted_po"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="converted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Converti le"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="converted_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="from_purchase_order",
                to="billing.invoice",
                verbose_name="Facture générée",
            ),
        ),
    ]
