# Generated by Django 5.0.2 on 2025-08-22 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_purchaseorder_converted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentline",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Quantité",
            ),
        ),
    ]
