# Generated by Django 5.0.2 on 2025-08-23 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0002_company_default_tax_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(max_length=50, verbose_name="Type de document"),
                ),
                (
                    "document_id",
                    models.PositiveIntegerField(verbose_name="ID du document"),
                ),
                (
                    "current_level",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Niveau actuel"
                    ),
                ),
                (
                    "total_levels",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Total des niveaux"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Montant",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'approbation",
                "verbose_name_plural": "Demandes d'approbation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Approbation"),
                            ("reject", "Rejet"),
                            ("cancel", "Annulation"),
                            ("comment", "Commentaire"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
                (
                    "approval_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="core.approvalrequest",
                        verbose_name="Demande d'approbation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'approbation",
                "verbose_name_plural": "Logs d'approbation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Facture"),
                            ("purchase_order", "Bon de commande"),
                            ("quote", "Devis"),
                            ("payment", "Paiement"),
                            ("journal_entry", "Écriture comptable"),
                            ("general", "Général"),
                        ],
                        max_length=50,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "approval_levels",
                    models.JSONField(
                        default=list,
                        help_text="Liste des niveaux avec rôles et seuils",
                        verbose_name="Niveaux d'approbation",
                    ),
                ),
                (
                    "amount_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Montant au-delà duquel l'approbation est requise",
                        max_digits=15,
                        null=True,
                        verbose_name="Seuil de montant",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow d'approbation",
                "verbose_name_plural": "Workflows d'approbation",
                "unique_together": {("name", "company")},
            },
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to="core.approvalworkflow",
                verbose_name="Workflow",
            ),
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("kpi", "Indicateur clé"),
                            ("chart", "Graphique"),
                            ("table", "Tableau"),
                            ("list", "Liste"),
                            ("gauge", "Jauge"),
                            ("progress", "Barre de progression"),
                        ],
                        max_length=20,
                        verbose_name="Type de widget",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titre")),
                (
                    "position",
                    models.JSONField(
                        default=dict,
                        help_text="Position x, y, width, height",
                        verbose_name="Position",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration spécifique au widget",
                        verbose_name="Paramètres",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget du tableau de bord",
                "verbose_name_plural": "Widgets du tableau de bord",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("success", "Succès"),
                            ("warning", "Avertissement"),
                            ("error", "Erreur"),
                            ("approval", "Approbation"),
                            ("reminder", "Rappel"),
                            ("system", "Système"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("normal", "Normale"),
                            ("high", "Élevée"),
                            ("urgent", "Urgente"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="URL d'action"
                    ),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Texte de l'action"
                    ),
                ),
                ("read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "dismissed",
                    models.BooleanField(default=False, verbose_name="Rejeté"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lu le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
