# Generated by Django 5.0.2 on 2025-08-23 04:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0002_company_default_tax_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("receivables", "Créances clients"),
                            ("payables", "Dettes fournisseurs"),
                        ],
                        max_length=20,
                        verbose_name="Type de rapport",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="Date du rapport")),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Montant à échéance",
                    ),
                ),
                (
                    "days_30_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="30 jours",
                    ),
                ),
                (
                    "days_60_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="60 jours",
                    ),
                ),
                (
                    "days_90_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="90 jours",
                    ),
                ),
                (
                    "days_120_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="120 jours",
                    ),
                ),
                (
                    "over_120_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Plus de 120 jours",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport de vieillissement",
                "verbose_name_plural": "Rapports de vieillissement",
                "ordering": ["-report_date"],
                "unique_together": {("company", "report_type", "report_date")},
            },
        ),
        migrations.CreateModel(
            name="CashFlowStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensuel"),
                            ("quarterly", "Trimestriel"),
                            ("yearly", "Annuel"),
                        ],
                        max_length=20,
                        verbose_name="Type de période",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "operating_cash_flow",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Flux d'exploitation",
                    ),
                ),
                (
                    "investing_cash_flow",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Flux d'investissement",
                    ),
                ),
                (
                    "financing_cash_flow",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Flux de financement",
                    ),
                ),
                (
                    "net_cash_change",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Variation nette de trésorerie",
                    ),
                ),
                (
                    "opening_cash",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Trésorerie d'ouverture",
                    ),
                ),
                (
                    "closing_cash",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Trésorerie de clôture",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "État des flux de trésorerie",
                "verbose_name_plural": "États des flux de trésorerie",
                "ordering": ["-end_date"],
                "unique_together": {
                    ("company", "period_type", "start_date", "end_date")
                },
            },
        ),
        migrations.CreateModel(
            name="ProfitLossStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensuel"),
                            ("quarterly", "Trimestriel"),
                            ("yearly", "Annuel"),
                        ],
                        max_length=20,
                        verbose_name="Type de période",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Chiffre d'affaires",
                    ),
                ),
                (
                    "other_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Autres produits",
                    ),
                ),
                (
                    "total_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total des produits",
                    ),
                ),
                (
                    "cost_of_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Coût des ventes",
                    ),
                ),
                (
                    "operating_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Charges d'exploitation",
                    ),
                ),
                (
                    "financial_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Charges financières",
                    ),
                ),
                (
                    "exceptional_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Charges exceptionnelles",
                    ),
                ),
                (
                    "total_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total des charges",
                    ),
                ),
                (
                    "operating_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Résultat d'exploitation",
                    ),
                ),
                (
                    "financial_result",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Résultat financier",
                    ),
                ),
                (
                    "exceptional_result",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Résultat exceptionnel",
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Résultat net",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte de résultat",
                "verbose_name_plural": "Comptes de résultat",
                "ordering": ["-end_date"],
                "unique_together": {
                    ("company", "period_type", "start_date", "end_date")
                },
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("trial_balance", "Balance des comptes"),
                            ("general_ledger", "Grand livre"),
                            ("vat_return", "Déclaration TVA"),
                            ("ar_ap", "Aged receivables/payables"),
                            ("cash_flow", "État des flux de trésorerie"),
                            ("profit_loss", "Compte de résultat"),
                            ("balance_sheet", "Bilan"),
                            ("inventory_report", "Rapport d'inventaire"),
                            ("sales_report", "Rapport des ventes"),
                            ("custom", "Rapport personnalisé"),
                        ],
                        max_length=50,
                        verbose_name="Type de rapport",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Quotidien"),
                            ("weekly", "Hebdomadaire"),
                            ("monthly", "Mensuel"),
                            ("quarterly", "Trimestriel"),
                            ("yearly", "Annuel"),
                        ],
                        max_length=20,
                        verbose_name="Fréquence",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Jour de la semaine (0-6, 0=Lundi)",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Jour du mois (1-31)"
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Mois (1-12)"
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        default=list,
                        help_text="Liste des adresses email",
                        verbose_name="Destinataires",
                    ),
                ),
                (
                    "cc_recipients",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Destinataires en copie"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Paramètres spécifiques au rapport",
                        verbose_name="Paramètres",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière exécution"
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Prochaine exécution"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Planification de rapport",
                "verbose_name_plural": "Planifications de rapports",
                "unique_together": {("name", "company")},
            },
        ),
    ]
