# Generated by Django 5.0.2 on 2024-01-01 00:00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom de la société')),
                ('ice', models.CharField(blank=True, help_text='Identifiant Commerce Entreprise', max_length=15, verbose_name='ICE')),
                ('if_field', models.CharField(blank=True, help_text='Identifiant Fiscal', max_length=15, verbose_name='IF')),
                ('rc', models.CharField(blank=True, help_text='Registre du Commerce', max_length=20, verbose_name='RC')),
                ('cnss', models.CharField(blank=True, help_text='Numéro CNSS', max_length=20, verbose_name='CNSS')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('country', models.CharField(default='Maroc', max_length=100, verbose_name='Pays')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('default_currency', models.CharField(choices=[('MAD', 'Dirham Marocain (MAD)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dollar US (USD)')], default='MAD', max_length=3, verbose_name='Devise par défaut')),
                ('current_fiscal_year', models.CharField(default='2024-2025', help_text='Format: YYYY-YYYY', max_length=9, verbose_name='Exercice fiscal en cours')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='Préférences')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Société',
                'verbose_name_plural': 'Sociétés',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('FAC', 'Facture'), ('DEV', 'Devis'), ('BC', 'Bon de commande'), ('AVOIR', 'Avoir'), ('RECU', 'Reçu'), ('BON', 'Bon de livraison')], max_length=10, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('pattern', models.CharField(default='{code}-{year}-{seq:04d}', help_text='Variables disponibles: {code}, {year}, {seq}, {month}', max_length=50, verbose_name='Modèle')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro')),
                ('prefix', models.CharField(blank=True, max_length=10, verbose_name='Préfixe')),
                ('suffix', models.CharField(blank=True, max_length=10, verbose_name='Suffixe')),
                ('reset_yearly', models.BooleanField(default=True, verbose_name='Remise à zéro annuelle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='companies.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Séquence',
                'verbose_name_plural': 'Séquences',
                'ordering': ['company', 'code'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
