# Generated by Django 5.0.2 on 2025-08-23 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_product_options_alter_taxrate_options_and_more"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="default_tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_companies",
                to="catalog.taxrate",
                verbose_name="Taux de TVA par défaut",
            ),
        ),
    ]
