# Generated by Django 5.0.2 on 2025-08-22 19:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom/Raison sociale"),
                ),
                (
                    "ice",
                    models.CharField(
                        blank=True,
                        help_text="Identifiant Commerce Entreprise",
                        max_length=15,
                        verbose_name="ICE",
                    ),
                ),
                (
                    "if_field",
                    models.CharField(
                        blank=True,
                        help_text="Identifiant Fiscal",
                        max_length=15,
                        verbose_name="IF",
                    ),
                ),
                (
                    "rc",
                    models.CharField(
                        blank=True,
                        help_text="Registre du Commerce",
                        max_length=20,
                        verbose_name="RC",
                    ),
                ),
                (
                    "is_customer",
                    models.BooleanField(default=False, verbose_name="Est un client"),
                ),
                (
                    "is_supplier",
                    models.BooleanField(
                        default=False, verbose_name="Est un fournisseur"
                    ),
                ),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("customer", "Client"),
                            ("supplier", "Fournisseur"),
                            ("both", "Client et Fournisseur"),
                        ],
                        default="customer",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=20, verbose_name="Mobile"),
                ),
                (
                    "billing_address",
                    models.TextField(blank=True, verbose_name="Adresse de facturation"),
                ),
                (
                    "shipping_address",
                    models.TextField(blank=True, verbose_name="Adresse de livraison"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code postal"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Maroc", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "payment_terms",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Nombre de jours pour le paiement",
                        verbose_name="Conditions de paiement (jours)",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Limite de crédit autorisée",
                        max_digits=12,
                        verbose_name="Limite de crédit",
                    ),
                ),
                (
                    "account_receivable",
                    models.CharField(
                        blank=True,
                        help_text="Compte comptable client (ex: 411)",
                        max_length=20,
                        verbose_name="Compte client",
                    ),
                ),
                (
                    "account_payable",
                    models.CharField(
                        blank=True,
                        help_text="Compte comptable fournisseur (ex: 401)",
                        max_length=20,
                        verbose_name="Compte fournisseur",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Tags séparés par des virgules",
                        max_length=200,
                        verbose_name="Tags",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="companies.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partie",
                "verbose_name_plural": "Parties",
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fonction"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=20, verbose_name="Mobile"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Contact principal"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="crm.party",
                        verbose_name="Partie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
