# Generated by Django 5.0.2 on 2025-08-23 22:23

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_default_tax_rate'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Contact principal')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.party', verbose_name='Partie')),
            ],
            options={
                'verbose_name': 'historical Contact',
                'verbose_name_plural': 'historical Contacts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalParty',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom/Raison sociale')),
                ('ice', models.CharField(blank=True, help_text='Identifiant Commerce Entreprise', max_length=15, verbose_name='ICE')),
                ('if_field', models.CharField(blank=True, help_text='Identifiant Fiscal', max_length=15, verbose_name='IF')),
                ('rc', models.CharField(blank=True, help_text='Registre du Commerce', max_length=20, verbose_name='RC')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Est un client')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Est un fournisseur')),
                ('party_type', models.CharField(choices=[('customer', 'Client'), ('supplier', 'Fournisseur'), ('both', 'Client et Fournisseur')], default='customer', max_length=20, verbose_name='Type')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile')),
                ('billing_address', models.TextField(blank=True, verbose_name='Adresse de facturation')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('country', models.CharField(default='Maroc', max_length=100, verbose_name='Pays')),
                ('payment_terms', models.PositiveIntegerField(default=30, help_text='Nombre de jours pour le paiement', verbose_name='Conditions de paiement (jours)')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Limite de crédit autorisée', max_digits=12, verbose_name='Limite de crédit')),
                ('account_receivable', models.CharField(blank=True, help_text='Compte comptable client (ex: 411)', max_length=20, verbose_name='Compte client')),
                ('account_payable', models.CharField(blank=True, help_text='Compte comptable fournisseur (ex: 401)', max_length=20, verbose_name='Compte fournisseur')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=200, verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company', verbose_name='Société')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Partie',
                'verbose_name_plural': 'historical Parties',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
