# Generated by Django 5.0.2 on 2025-08-23 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_historicalpricelist_pricelist_pricelistitem'),
        ('crm', '0002_historicalcontact_historicalparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparty',
            name='price_list',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.pricelist', verbose_name='Liste de prix'),
        ),
        migrations.AddField(
            model_name='party',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.pricelist', verbose_name='Liste de prix'),
        ),
    ]
