# Generated by Django 5.0.2 on 2025-08-24 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_historicalparty_price_list_party_price_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalparty',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='party',
            name='price_list',
        ),
    ]
