# Generated by Django 5.0.2 on 2025-08-22 19:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_categories",
                        to="companies.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.productcategory",
                        verbose_name="Catégorie parente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie de produit",
                "verbose_name_plural": "Catégories de produits",
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: TVA 20%, TVA 10%, Exonéré",
                        max_length=100,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Taux en pourcentage (ex: 20.00 pour 20%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Taux (%)",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Code interne (ex: TVA20, TVA10, EXO)",
                        max_length=10,
                        verbose_name="Code",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Date d'application du taux",
                        null=True,
                        verbose_name="Date de début",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date de fin d'application du taux",
                        null=True,
                        verbose_name="Date de fin",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laissez vide pour un taux global",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_rates",
                        to="companies.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taux de TVA",
                "verbose_name_plural": "Taux de TVA",
                "ordering": ["rate", "name"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code produit unique",
                        max_length=50,
                        verbose_name="Code",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("product", "Produit/Article"),
                            ("service", "Service"),
                        ],
                        default="product",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "price_ht",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Prix HT",
                    ),
                ),
                (
                    "has_stock",
                    models.BooleanField(
                        default=False, verbose_name="Gestion des stocks"
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité en stock"
                    ),
                ),
                (
                    "min_stock",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Alerte quand le stock descend sous cette valeur",
                        verbose_name="Stock minimum",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="pièce",
                        help_text="Ex: pièce, kg, m, heure, jour",
                        max_length=20,
                        verbose_name="Unité",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="companies.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.productcategory",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.taxrate",
                        verbose_name="Taux de TVA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit/Service",
                "verbose_name_plural": "Produits/Services",
                "ordering": ["name"],
                "unique_together": {("company", "code")},
            },
        ),
    ]
