# Generated by Django 5.0.2 on 2025-08-23 04:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Produit", "verbose_name_plural": "Produits"},
        ),
        migrations.AlterModelOptions(
            name="taxrate",
            options={
                "verbose_name": "Taux de TVA",
                "verbose_name_plural": "Taux de TVA",
            },
        ),
        # Ensure 'sku' exists before applying unique_together on it
        migrations.AlterUniqueTogether(
            name="taxrate",
            unique_together={("rate", "company")},
        ),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Code-barres"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="current_stock",
            field=models.PositiveIntegerField(default=0, verbose_name="Stock actuel"),
        ),
        migrations.AddField(
            model_name="product",
            name="max_stock",
            field=models.PositiveIntegerField(
                default=1000, verbose_name="Stock maximum"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("product", "Produit"), ("service", "Service")],
                default="product",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Référence"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("sku", "company")},
        ),
        migrations.AlterField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.company"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="has_stock",
            field=models.BooleanField(default=False, verbose_name="Gestion de stock"),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_stock",
            field=models.PositiveIntegerField(default=0, verbose_name="Stock minimum"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_ht",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Prix HT",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.taxrate",
            ),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="rate",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Taux (%)"
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "unique_together": {("name", "company")},
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.category",
            ),
        ),
        migrations.CreateModel(
            name="ProductStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_stock",
                    models.PositiveIntegerField(default=0, verbose_name="Stock actuel"),
                ),
                (
                    "min_stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Stock minimum"
                    ),
                ),
                (
                    "max_stock",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Stock maximum"
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Coût moyen",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_info",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock produit",
                "verbose_name_plural": "Stocks produits",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "Entrée"),
                            ("out", "Sortie"),
                            ("adjustment", "Ajustement"),
                            ("transfer", "Transfert"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantité")),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Coût unitaire",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Type de référence"
                    ),
                ),
                ("reference_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "stock_before",
                    models.PositiveIntegerField(verbose_name="Stock avant"),
                ),
                (
                    "stock_after",
                    models.PositiveIntegerField(verbose_name="Stock après"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="code",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock_quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="code",
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="description",
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="updated_at",
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
    ]
