# Generated by Django 5.0.2 on 2025-08-23 22:45

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_historicalcategory_historicalproduct_and_more'),
        ('companies', '0002_company_default_tax_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPriceList',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('currency', models.CharField(default='MAD', max_length=3, verbose_name='Devise')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Liste de prix',
                'verbose_name_plural': 'historical Listes de prix',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('currency', models.CharField(default='MAD', max_length=3, verbose_name='Devise')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'verbose_name': 'Liste de prix',
                'verbose_name_plural': 'Listes de prix',
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_price_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix HT fixé')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Remise (%)')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Règle de prix',
                'verbose_name_plural': 'Règles de prix',
                'unique_together': {('price_list', 'product')},
            },
        ),
    ]
