# Generated by Django 5.0.2 on 2025-08-24 03:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_historicalpricelist_pricelist_pricelistitem'),
        ('companies', '0002_company_default_tax_rate'),
        ('crm', '0004_remove_historicalparty_price_list_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom de la session')),
                ('scope_type', models.CharField(choices=[('all', 'Tous les produits'), ('category', 'Catégorie')], default='all', max_length=20, verbose_name='Périmètre')),
                ('is_blind', models.BooleanField(default=False, verbose_name='Comptage à l’aveugle')),
                ('freeze_stock', models.BooleanField(default=False, verbose_name='Geler mouvements pendant inventaire')),
                ('tolerance_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tolérance %')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot de départ')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'En cours'), ('closed', 'Clôturé')], default='draft', max_length=20, verbose_name='Statut')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Démarré le')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Clôturé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'inventaire",
                'verbose_name_plural': "Sessions d'inventaire",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_qty', models.IntegerField(default=0, verbose_name='Stock au départ')),
                ('counted_qty', models.IntegerField(blank=True, null=True, verbose_name='Quantité comptée')),
                ('recounted_qty', models.IntegerField(blank=True, null=True, verbose_name='Recomptage')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('counted', 'Compté'), ('validated', 'Validé'), ('flagged', 'Recomptage')], default='pending', max_length=20, verbose_name='Statut')),
                ('zone', models.CharField(blank=True, max_length=64, verbose_name='Zone/Emplacement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_assigned', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='catalog.inventorysession')),
            ],
            options={
                'verbose_name': "Comptage d'inventaire",
                'verbose_name_plural': "Comptages d'inventaire",
                'unique_together': {('session', 'product')},
            },
        ),
    ]
