# Generated by Django 5.0.2 on 2025-08-24 04:42

from django.db import migrations, models


def dedupe_sku_company(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    db_alias = schema_editor.connection.alias
    seen = set()
    for p in Product.objects.using(db_alias).all().order_by('id'):
        key = (p.sku or '', p.company_id)
        if key in seen:
            base = (p.sku or '').strip()
            if not base:
                base = 'GEN'
            # Ensure new sku is unique
            new_sku = f"{base}-{p.id}"
            p.sku = new_sku
            p.save(update_fields=['sku'])
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_pricelist_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_sku_company, migrations.RunPython.noop),
        migrations.AddField(
            model_name='historicalproduct',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Code'),
        ),
    ]
