# Generated by Django 5.0.2 on 2025-08-24 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_pricelist_unique_together_and_more'),
    ]

    operations = [
        # Keep migration state in sync while avoiding duplicate columns on DB
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='taxrate',
                    name='code',
                    field=models.CharField(blank=True, default='', max_length=100, verbose_name='Code'),
                ),
                migrations.AddField(
                    model_name='taxrate',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='taxrate',
                    name='description',
                    field=models.TextField(blank=True, default='', verbose_name='Description'),
                ),
                migrations.AddField(
                    model_name='taxrate',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
                ),
            ],
        ),
    ]
