# Generated by Django 5.0.2 on 2025-08-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_pricelist_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='current_stock',
            field=models.IntegerField(default=0, verbose_name='Stock actuel'),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='stock_after',
            field=models.IntegerField(verbose_name='Stock après'),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='stock_before',
            field=models.IntegerField(verbose_name='Stock avant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=0, verbose_name='Stock actuel'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='stock_after',
            field=models.IntegerField(verbose_name='Stock après'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='stock_before',
            field=models.IntegerField(verbose_name='Stock avant'),
        ),
    ]
