# Generated by Django 5.0.2 on 2025-08-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_historicalproduct_current_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductstock',
            name='current_stock',
            field=models.IntegerField(default=0, verbose_name='Stock actuel'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='current_stock',
            field=models.IntegerField(default=0, verbose_name='Stock actuel'),
        ),
    ]
