# Generated by Django 5.0.2 on 2025-08-24 13:51
#
# Suppression du modèle PriceList (fonctionnalité retirée des models).
# On utilise uniquement DeleteModel : la combinaison RemoveField + DeleteModel
# du même groupe de modèles provoque une erreur "NewPriceListItem has no field
# named 'price_list'" lors de la remise en forme des tables sous SQLite.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_pricelist_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(name='PriceListItem'),
        migrations.DeleteModel(name='PriceList'),
        migrations.DeleteModel(name='HistoricalPriceList'),
    ]
