# Generated by Django 5.0.2 on 2025-08-22 19:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="VatPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Début de période")),
                ("period_end", models.DateField(verbose_name="Fin de période")),
                (
                    "frequency",
                    models.CharField(
                        choices=[("monthly", "Mensuel"), ("quarterly", "Trimestriel")],
                        default="monthly",
                        max_length=20,
                        verbose_name="Fréquence",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("closed", "Fermé"),
                            ("submitted", "Soumis"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "vat_collected",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="TVA collectée",
                    ),
                ),
                (
                    "vat_deductible",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="TVA déductible",
                    ),
                ),
                (
                    "vat_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="TVA à payer",
                    ),
                ),
                (
                    "vat_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Crédit de TVA",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Période TVA",
                "verbose_name_plural": "Périodes TVA",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le code doit contenir 1 à 8 chiffres.",
                                regex="^[0-9]{1,8}$",
                            )
                        ],
                        verbose_name="Code",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Actif"),
                            ("liability", "Passif"),
                            ("equity", "Capitaux propres"),
                            ("income", "Produits"),
                            ("expense", "Charges"),
                            ("tax", "Taxes"),
                            ("receivable", "Créances"),
                            ("payable", "Dettes"),
                            ("cash", "Trésorerie"),
                            ("bank", "Banque"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(default=1, verbose_name="Niveau"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "allow_manual_entries",
                    models.BooleanField(
                        default=True, verbose_name="Autoriser saisie manuelle"
                    ),
                ),
                (
                    "require_analytics",
                    models.BooleanField(
                        default=False, verbose_name="Requiert analytique"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="companies.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="accounting.account",
                        verbose_name="Compte parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte",
                "verbose_name_plural": "Comptes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le code doit contenir 2 à 10 caractères majuscules et chiffres.",
                                regex="^[A-Z0-9]{2,10}$",
                            )
                        ],
                        verbose_name="Code",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "journal_type",
                    models.CharField(
                        choices=[
                            ("VEN", "Ventes"),
                            ("ACH", "Achats"),
                            ("BQ", "Banque"),
                            ("CAI", "Caisse"),
                            ("MIS", "Divers"),
                            ("OD", "Opérations diverses"),
                        ],
                        default="MIS",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "allow_negative_balance",
                    models.BooleanField(
                        default=False, verbose_name="Autoriser solde négatif"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journals",
                        to="companies.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal",
                "verbose_name_plural": "Journaux",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Date")),
                (
                    "ref",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Libellé")),
                (
                    "posted",
                    models.BooleanField(default=False, verbose_name="Comptabilisé"),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Comptabilisé le"
                    ),
                ),
                (
                    "total_debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total débit",
                    ),
                ),
                (
                    "total_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total crédit",
                    ),
                ),
                (
                    "origin_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID d'origine"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="companies.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="accounting.journal",
                        verbose_name="Journal",
                    ),
                ),
                (
                    "origin_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Type d'origine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Écriture",
                "verbose_name_plural": "Écritures",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MoveLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Débit",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Crédit",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MAD", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=10,
                        verbose_name="Taux de change",
                    ),
                ),
                (
                    "reconciled_group",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Groupe de lettrage"
                    ),
                ),
                (
                    "reconciled",
                    models.BooleanField(default=False, verbose_name="Lettré"),
                ),
                (
                    "analytical_account",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Compte analytique"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_lines",
                        to="accounting.account",
                        verbose_name="Compte",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.move",
                        verbose_name="Écriture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'écriture",
                "verbose_name_plural": "Lignes d'écriture",
                "ordering": ["id"],
            },
        ),
    ]
