# Generated by Django 5.0.2 on 2025-08-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("companies", "0001_initial"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moveline",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="move_lines",
                to="crm.party",
                verbose_name="Partie",
            ),
        ),
        migrations.AddField(
            model_name="vatperiod",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vat_periods",
                to="companies.company",
                verbose_name="Société",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("company", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="journal",
            unique_together={("company", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="vatperiod",
            unique_together={("company", "period_start", "period_end")},
        ),
    ]
