# Generated by Django 5.0.2 on 2025-08-23 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Début")),
                ("end_date", models.DateField(verbose_name="Fin")),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Clôturé"),
                ),
                (
                    "locked_until",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Période verrouillée jusqu'au",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_years",
                        to="companies.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercice fiscal",
                "verbose_name_plural": "Exercices fiscaux",
                "ordering": ["-start_date"],
                "unique_together": {("company", "start_date", "end_date")},
            },
        ),
    ]
